### ISSUE TITLE
Using `lmcache_vllm serve` command cannot activate lmcache

### ISSUE THREAD

**Issue by YaoJiayi** [LMCache/lmcache-tests#12]

**Comment by qyy2003** [comment]
I thought it worked well, according to my previous experiment.

**Comment by XbzOnGit** [comment]
I found four ways to workaround this problem. __Any__ of them should work. But none is perfect.  
For a details on why it is hard to fix it perfectly. I attached a pdf here. It is too long.  
[report.pdf](https://github.com/user-attachments/files/17245847/report.pdf)



1. Use python3 -m lmcache_vllm.vllm.entrypoints.openai.api_server to launch.  
This is inconvient.  
2. install without -e  
It is inconvient for developers, but should work for users.  
3. Pass --disable-frontend-multiprocessing.   
This can hurt performance, cos it puts the engine and the api server into the same process.  
We can append the flag to sys.argv in lmcache_vllm \_\_init\_\_.py to always disable it.  
4. Replace entry_points with scripts in setup.py of lmcache_vllm.  
Use a script that will always import lmcache_vllm.  
Delete entry_points from setup.py and add scripts = ["scripts/lmcache_vllm"],  
(Manually specify a script which always imports lmcache_vllm, not generated by pip).  
Easy to add into setup code.  
But this hurts portability. Because a shebang working on linux might not work on other OS.  
scripts/lmcache_vllm is 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys
from lmcache_vllm.script import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by YaoJiayi** [comment]
Cool. Thanks Sixian! Let's stick to the current solution (#1).
